### ISSUE TITLE
Unhandled exception: java.nio.channels.AsynchronousCloseException: null

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/nfs4j-daemon#2]
```
2018-12-16 23:46:58.438 [192.168.1.100/192.168.1.100:731] [nfs4j@2048 (11)] ERROR o.d.n.v.NFSServerV41 - Unhandled exception:
java.nio.channels.AsynchronousCloseException: null
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
        at java.base/sun.nio.ch.FileChannelImpl.writeInternal(FileChannelImpl.java:861)
        at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:839)
        at io.github.toilal.nsf4j.fs.io.FileSystemReaderWriter.write(FileSystemReaderWriter.java:55)
        at io.github.toilal.nsf4j.fs.AbstractNioFileSystem.write(AbstractNioFileSystem.java:347)
        at io.github.toilal.nsf4j.fs.RootFileSystem.write(RootFileSystem.java:188)
        at org.dcache.nfs.vfs.PseudoFs.write(PseudoFs.java:291)
        at org.dcache.nfs.v4.OperationWRITE.process(OperationWRITE.java:82)
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:204)
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48)
        at org.dcache.oncrpc4j.rpc.RpcDispatcher$1.run(RpcDispatcher.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

It has occured when copying a big file with this command

```
dd if=/dev/zero of=/mnt/nfs4j/testfile-nfs4j bs=1024MB count=1
```

**Comment by ruanimal** [comment]
Is there any way to solve this problem?

with windows server
- macOS client has this bug
- ubuntu client seems to be ok
